"""create tables: users, transactions, tasks

Revision ID: 70e163568918
Revises: 
Create Date: 2024-05-27 13:51:45.525298

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "70e163568918"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("username", sa.String(length=26), nullable=False),
        sa.Column("email", sa.String(length=36), nullable=False),
        sa.Column("password", sa.String(length=40), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "tasks",
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("is_completed", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "transactions",
        sa.Column(
            "type", sa.Enum("INCOME", "EXPENSE", name="typeoperation"), nullable=False
        ),
        sa.Column(
            "category",
            sa.Enum(
                "SALARY",
                "FOOD",
                "TRANSPORTATION",
                "HOUSEHOLD",
                "ENTERTAINMENT",
                "HEALTH",
                "EDUCATION",
                "TRAVEL",
                "OTHER",
                name="category",
            ),
            nullable=False,
        ),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("price", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "date",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transactions")
    op.drop_table("tasks")
    op.drop_table("users")
    # ### end Alembic commands ###
